[window]
decorations = "none"
opacity = 0.75 # Matching the "Shadow" atmosphere

[colors.primary]
background = "#10090B" # Void Black
foreground = "#7F7A7B" # Moonlit White

[colors.normal]
black   = "#120B0D"
red     = "#B91A3B"
green   = "#D81D43"
yellow  = "#B91A3B"
blue    = "#D51D42" # Sword Glow Red
magenta = "#8D162F"
cyan    = "#C31B3D"
white   = "#7F7A7B"