[window]
decorations = "none"
opacity = 0.75 # Matching the "Shadow" atmosphere

[colors.primary]
background = "#07080A" # Void Black
foreground = "#DADBDD" # Moonlit White

[colors.normal]
black   = "#101216"
red     = "#D61521"
green   = "#FF3039"
yellow  = "#CF1622"
blue    = "#F0222D" # Sword Glow Red
magenta = "#B41924"
cyan    = "#E11A26"
white   = "#DADBDD"