accent = "#B91A3B"
cursor = "#D51D42"
foreground = "#7F7A7B"
background = "#10090B"
selection_foreground = "#7F7A7B"
selection_background = "#44161C"

color0 = "#120B0D"
color1 = "#1F0D10"
color2 = "#44161C"
color3 = "#4B111C"
color4 = "#601523"
color5 = "#8D162F"
color6 = "#C31B3D"
color7 = "#7F7A7B"
color8 = "#160A0D"
color9 = "#D51D42"
color10 = "#D81D43"
color11 = "#DA2045"
color12 = "#DA2045"
color13 = "#DA2045"
color14 = "#7F7A7B"
color15 = "#7F7A7B"
